### PR TITLE
Team6 project final

### PR DESCRIPTION
**Pull request by raeland**
Yuki is the ROCK STAR, Rune is the idea man, Carolina is the swagger queen, Rachael is the videographer

### CODE REVIEW

**Review by raeland — COMMENTED** [review]
perfection

**Review by raeland — COMMENTED** [review]
perfection twice

**Review by theonlyruneyouknow — APPROVED** [review]
Approved!

**Review by theonlyruneyouknow — APPROVED** [review]
Approved!

**Review by theonlyruneyouknow — APPROVED** [review]

**Review by theonlyruneyouknow — COMMENTED** [review]
Approved!

**Review by theonlyruneyouknow — APPROVED** [review]
Approved!

**Pull request merged**
